.\" Manpage for pokemon_client.
.TH man 8 "14 May 2018" "1.0" "pokemon_client man page"
.SH NAME
pokemon_server \- Aplicacion de servidor que simula la captura de Pokemons.
.SH SYNOPSIS
.B pokemon_server
.SH DESCRIPTION
El servidor recibe la solicitud de los clientes para atrapar algún pokemon. Se le ofrecera algún Pokemon aleatorio
cual el cliente tendra n intenteos para atraparlo.
