codes = {
    'hello': 1,
    'question': 2,
    'trainers': 3,
    'id':4,
    'password':5,
    'do_not_have_pokemon':6,
    'request_pokemon': 10,
    'capturing_verification': 20,
    'attemps': 21,
    'captured': 22,
    'no_attemps': 23,
    'yes': 30,
    'no': 31,
    'terminated_session': 32,
    'pokemon_list': 33,
    'image_received':  12,
    'id_not_found':41,
    'pass_no_match':42,
    'already_have_pokemon':43,
    'already_have_all':44,
    'active_user': 45,
    'timeout': 46

}
